name: control_parental
description: "MVP para control parental de dispositivo de sueño infantil."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Gestión de estado
  flutter_riverpod: ^2.4.9
  
  # Navegación declarativa
  go_router: ^12.1.1
  
  # UI y Diseño (Fuentes amigables)
  google_fonts: ^6.1.0
  
  # Gráficas para estadísticas
  fl_chart: ^0.65.0
  
  # Formateo de fechas
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true